import { ToolConfig, CategoryId, ProcessorType } from '../types';

export const tools: ToolConfig[] = [
  // --- Basic Editing ---
  { id: 'blur-background', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], name: 'Blur Background', slug: 'blur-background', category: 'basic-editing', icon: 'Image', accentColor: '#6366F1', description: 'Blur the background of an image using AI', metaTitle: 'Blur Background Online', metaDescription: 'Easily blur image backgrounds instantly.', acceptedFormats: ['image/jpeg', 'image/png', 'image/webp'], maxFileSize: 20 * 1024 * 1024, multiFile: false, options: [], processor: 'blur', comingSoon: true },
  { id: 'remove-background', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], name: 'Remove Background', slug: 'remove-background', category: 'basic-editing', icon: 'Scissors', accentColor: '#6366F1', description: 'Remove the background from images automatically', metaTitle: 'Remove Background Online', metaDescription: 'Remove image background online for free.', acceptedFormats: ['image/jpeg', 'image/png', 'image/webp'], maxFileSize: 20 * 1024 * 1024, multiFile: false, options: [], processor: 'background-remove', comingSoon: true },
  { id: 'remove-object', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], name: 'Remove Object from Photo', slug: 'remove-object-from-photo', category: 'basic-editing', icon: 'Eraser', accentColor: '#6366F1', description: 'Erase unwanted objects from photos', metaTitle: 'Remove Objects from Photo Online', metaDescription: 'Remove any object from your photo easily.', acceptedFormats: ['image/jpeg', 'image/png', 'image/webp'], maxFileSize: 20 * 1024 * 1024, multiFile: false, options: [], processor: 'coming-soon', comingSoon: true },
  { id: 'add-name-dob', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], name: 'Add Name & DOB on Photo', slug: 'add-name-dob-on-photo', category: 'basic-editing', icon: 'Type', accentColor: '#6366F1', description: 'Add your Name and Date of Birth to photos for official forms', metaTitle: 'Add Name and Date of Birth on Photo', metaDescription: 'Add name and DOB to your passport photo easily.', acceptedFormats: ['image/jpeg', 'image/png'], maxFileSize: 10 * 1024 * 1024, multiFile: false, options: [
    { id: 'name', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], label: 'Name', type: 'text' as any, defaultValue: '' },
    { id: 'dob', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], label: 'DOB', type: 'text' as any, defaultValue: '' }
  ], processor: 'text-overlay' },
  { id: 'rotate', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], name: 'Rotate', slug: 'rotate-image', category: 'basic-editing', icon: 'RotateCw', accentColor: '#6366F1', description: 'Rotate image by 90, 180, or 270 degrees', metaTitle: 'Rotate Image Online', metaDescription: 'Rotate your photos online quickly and easily.', acceptedFormats: ['image/jpeg', 'image/png', 'image/webp'], maxFileSize: 20 * 1024 * 1024, multiFile: true, options: [
    { id: 'angle', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], label: 'Angle', type: 'segmented', defaultValue: 90, chips: [{ label: '90°', value: 90 }, { label: '180°', value: 180 }, { label: '270°', value: 270 }] }
  ], processor: 'rotate' },
  { id: 'flip', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], name: 'Flip', slug: 'flip-image', category: 'basic-editing', icon: 'FlipHorizontal', accentColor: '#6366F1', description: 'Flip your image horizontally or vertically', metaTitle: 'Flip Image Online', metaDescription: 'Flip your images horizontally or vertically online.', acceptedFormats: ['image/jpeg', 'image/png', 'image/webp'], maxFileSize: 20 * 1024 * 1024, multiFile: true, options: [
    { id: 'direction', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], label: 'Direction', type: 'segmented', defaultValue: 'horizontal', options: [{ label: 'Horizontal', value: 'horizontal' }, { label: 'Vertical', value: 'vertical' }] }
  ], processor: 'flip' },
  { id: 'watermark', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], name: 'Watermark', slug: 'add-watermark', category: 'basic-editing', icon: 'Stamp', accentColor: '#6366F1', description: 'Add a text or image watermark to your photos', metaTitle: 'Add Watermark to Photo', metaDescription: 'Protect your images by adding a watermark.', acceptedFormats: ['image/jpeg', 'image/png', 'image/webp'], maxFileSize: 20 * 1024 * 1024, multiFile: true, options: [
    { id: 'text', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], label: 'Watermark Text', type: 'text' as any, defaultValue: 'Watermark' },
    { id: 'opacity', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], label: 'Opacity', type: 'slider', defaultValue: 50, min: 0, max: 100 }
  ], processor: 'watermark' },
  { id: 'freehand-crop', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], name: 'Freehand Crop', slug: 'freehand-crop', category: 'basic-editing', icon: 'Crop', accentColor: '#6366F1', description: 'Crop your image freely', metaTitle: 'Freehand Crop Image Online', metaDescription: 'Crop images freehand online.', acceptedFormats: ['image/jpeg', 'image/png', 'image/webp'], maxFileSize: 20 * 1024 * 1024, multiFile: false, options: [], processor: 'crop' },
  { id: 'circle-crop', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], name: 'Circle Crop', slug: 'circle-crop', category: 'basic-editing', icon: 'Circle', accentColor: '#6366F1', description: 'Crop your image into a perfect circle', metaTitle: 'Circle Crop Online', metaDescription: 'Crop your photos into a circle shape.', acceptedFormats: ['image/jpeg', 'image/png', 'image/webp'], maxFileSize: 20 * 1024 * 1024, multiFile: false, options: [], processor: 'crop', processorConfig: { shape: 'circle' } },
  { id: 'square-crop', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], name: 'Square Crop', slug: 'square-crop', category: 'basic-editing', icon: 'Square', accentColor: '#6366F1', description: 'Crop your image into a square (1:1)', metaTitle: 'Square Crop Online', metaDescription: 'Crop images into a square shape.', acceptedFormats: ['image/jpeg', 'image/png', 'image/webp'], maxFileSize: 20 * 1024 * 1024, multiFile: false, options: [], processor: 'crop', processorConfig: { aspectRatio: 1 } },
  { id: 'round-corners', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], name: 'Round Corners', slug: 'round-corners', category: 'basic-editing', icon: 'AppWindow', accentColor: '#6366F1', description: 'Add rounded corners to your image', metaTitle: 'Round Image Corners', metaDescription: 'Easily round the corners of your images.', acceptedFormats: ['image/jpeg', 'image/png', 'image/webp'], maxFileSize: 20 * 1024 * 1024, multiFile: true, options: [
    { id: 'radius', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], label: 'Border Radius', type: 'slider', defaultValue: 20, min: 1, max: 100 }
  ], processor: 'border', processorConfig: { type: 'rounded' } },
  { id: 'change-aspect-ratio', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], name: 'Change Aspect Ratio', slug: 'change-aspect-ratio', category: 'basic-editing', icon: 'Scaling', accentColor: '#6366F1', description: 'Change the aspect ratio of your image without cropping', metaTitle: 'Change Aspect Ratio Online', metaDescription: 'Adjust image aspect ratio online.', acceptedFormats: ['image/jpeg', 'image/png', 'image/webp'], maxFileSize: 20 * 1024 * 1024, multiFile: false, options: [
    { id: 'ratio', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], label: 'Aspect Ratio', type: 'select', defaultValue: '16:9', options: [{ label: '16:9', value: '16:9' }, { label: '4:3', value: '4:3' }, { label: '1:1', value: '1:1' }] }
  ], processor: 'crop' },
  { id: 'merge-photo-signature', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], name: 'Merge Photo & Signature', slug: 'merge-photo-signature', category: 'basic-editing', icon: 'FileImage', accentColor: '#6366F1', description: 'Combine your passport photo and signature', metaTitle: 'Merge Photo and Signature', metaDescription: 'Merge passport photo and signature for applications.', acceptedFormats: ['image/jpeg', 'image/png'], maxFileSize: 10 * 1024 * 1024, multiFile: true, options: [], processor: 'merge' },
  { id: 'join-multiple-images', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], name: 'Join Multiple Images', slug: 'join-images', category: 'basic-editing', icon: 'Columns', accentColor: '#6366F1', description: 'Join multiple images together horizontally or vertically', metaTitle: 'Join Images Online', metaDescription: 'Combine multiple images into one.', acceptedFormats: ['image/jpeg', 'image/png', 'image/webp'], maxFileSize: 20 * 1024 * 1024, multiFile: true, options: [
    { id: 'layout', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], label: 'Layout', type: 'segmented', defaultValue: 'vertical', options: [{ label: 'Vertical', value: 'vertical' }, { label: 'Horizontal', value: 'horizontal' }] }
  ], processor: 'merge' },
  { id: 'split-image', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], name: 'Split Image', slug: 'split-image', category: 'basic-editing', icon: 'SplitSquareHorizontal', accentColor: '#6366F1', description: 'Split one image into multiple parts', metaTitle: 'Split Image Online', metaDescription: 'Divide your image into a grid of smaller images.', acceptedFormats: ['image/jpeg', 'image/png', 'image/webp'], maxFileSize: 20 * 1024 * 1024, multiFile: false, options: [
    { id: 'rows', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], label: 'Rows', type: 'number', defaultValue: 2, min: 1, max: 10 },
    { id: 'cols', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], label: 'Columns', type: 'number', defaultValue: 2, min: 1, max: 10 }
  ], processor: 'split' },
  { id: 'image-color-picker', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], name: 'Image Color Picker', slug: 'image-color-picker', category: 'basic-editing', icon: 'Pipette', accentColor: '#6366F1', description: 'Extract exact HEX, RGB or HSL colors from your image', metaTitle: 'Image Color Picker Online', metaDescription: 'Pick colors from an image instantly.', acceptedFormats: ['image/jpeg', 'image/png', 'image/webp'], maxFileSize: 20 * 1024 * 1024, multiFile: false, options: [], processor: 'color-picker' },
  { id: 'edit-metadata', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], name: 'Edit Metadata', slug: 'edit-image-metadata', category: 'basic-editing', icon: 'FileEdit', accentColor: '#6366F1', description: 'Edit EXIF metadata of your image files', metaTitle: 'Edit EXIF Data Online', metaDescription: 'Modify image EXIF data securely.', acceptedFormats: ['image/jpeg', 'image/png', 'image/webp'], maxFileSize: 20 * 1024 * 1024, multiFile: false, comingSoon: true, options: [], processor: 'metadata', processorConfig: { action: 'edit' } },
  { id: 'view-metadata', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], name: 'View Metadata', slug: 'view-image-metadata', category: 'basic-editing', icon: 'Eye', accentColor: '#6366F1', description: 'View hidden EXIF and metadata information inside your photos', metaTitle: 'View EXIF Data Online', metaDescription: 'Check all metadata contained in your photos.', acceptedFormats: ['image/jpeg', 'image/png', 'image/webp'], maxFileSize: 20 * 1024 * 1024, multiFile: false, comingSoon: true, options: [], processor: 'metadata', processorConfig: { action: 'view' } },
  { id: 'remove-metadata', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], name: 'Remove Metadata', slug: 'remove-image-metadata', category: 'basic-editing', icon: 'Shield', accentColor: '#6366F1', description: 'Strip all EXIF metadata for privacy before sharing', metaTitle: 'Remove EXIF Data Online', metaDescription: 'Strip metadata from your images to protect your privacy.', acceptedFormats: ['image/jpeg', 'image/png', 'image/webp'], maxFileSize: 20 * 1024 * 1024, multiFile: true, options: [], processor: 'metadata', processorConfig: { action: 'remove' } },
  { id: 'crop-png', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], name: 'Crop PNG', slug: 'crop-png', category: 'basic-editing', icon: 'Crop', accentColor: '#6366F1', description: 'Crop transparent PNG files without losing transparency', metaTitle: 'Crop PNG Image', metaDescription: 'Crop PNG files easily while retaining transparency.', acceptedFormats: ['image/png'], maxFileSize: 20 * 1024 * 1024, multiFile: false, options: [], processor: 'crop' },

  // --- Effects ---
  { id: 'beautify-image', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], name: 'Beautify Image', slug: 'beautify-image', category: 'effects', icon: 'Wand2', accentColor: '#EC4899', description: 'Enhance your photo with automatic beauty filters', metaTitle: 'Beautify Photo Online', metaDescription: 'Apply automatic beautification to your photos.', acceptedFormats: ['image/jpeg', 'image/png', 'image/webp'], maxFileSize: 20 * 1024 * 1024, multiFile: false, options: [], processor: 'ai-enhance', comingSoon: true },
  { id: 'deep-fry', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], name: 'Deep Fry Photo', slug: 'deep-fry-photo', category: 'effects', icon: 'Flame', accentColor: '#EC4899', description: 'Apply deep fried meme filters to your images', metaTitle: 'Deep Fry Photo Maker', metaDescription: 'Create deep fried meme images instantly.', acceptedFormats: ['image/jpeg', 'image/png', 'image/webp'], maxFileSize: 20 * 1024 * 1024, multiFile: false, options: [
    { id: 'intensity', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], label: 'Fry Level', type: 'slider', defaultValue: 50, min: 0, max: 100 }
  ], processor: 'filter' },
  { id: 'unblur-image', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], name: 'Unblur Image', slug: 'unblur-image', category: 'effects', icon: 'Focus', accentColor: '#EC4899', description: 'Sharpen blurry images using AI', metaTitle: 'Unblur Image Online', metaDescription: 'Sharpen and unblur your images.', acceptedFormats: ['image/jpeg', 'image/png', 'image/webp'], maxFileSize: 20 * 1024 * 1024, multiFile: false, options: [], processor: 'ai-enhance', comingSoon: true },
  { id: 'blur-image', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], name: 'Blur Image', slug: 'blur-image', category: 'effects', icon: 'Droplets', accentColor: '#EC4899', description: 'Apply a blur effect to your entire image', metaTitle: 'Blur Image Online', metaDescription: 'Easily blur images online.', acceptedFormats: ['image/jpeg', 'image/png', 'image/webp'], maxFileSize: 20 * 1024 * 1024, multiFile: true, options: [
    { id: 'radius', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], label: 'Blur Radius', type: 'slider', defaultValue: 10, min: 1, max: 100 }
  ], processor: 'blur' },
  { id: 'blur-face', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], name: 'Blur Face', slug: 'blur-face', category: 'effects', icon: 'VenetianMask', accentColor: '#EC4899', description: 'Automatically detect and blur faces for privacy', metaTitle: 'Blur Face in Photo', metaDescription: 'Blur faces in photos securely.', acceptedFormats: ['image/jpeg', 'image/png', 'image/webp'], maxFileSize: 20 * 1024 * 1024, multiFile: false, options: [], processor: 'coming-soon', comingSoon: true },
  { id: 'unblur-face', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], name: 'Unblur Face', slug: 'unblur-face', category: 'effects', icon: 'ScanFace', accentColor: '#EC4899', description: 'Restore and unblur faces using AI enhancement', metaTitle: 'Unblur Face Online', metaDescription: 'Sharpen blurry faces in photos using AI.', acceptedFormats: ['image/jpeg', 'image/png', 'image/webp'], maxFileSize: 20 * 1024 * 1024, multiFile: false, options: [], processor: 'ai-enhance', comingSoon: true },
  { id: 'add-border', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], name: 'Add Border', slug: 'add-border-to-image', category: 'effects', icon: 'Square', accentColor: '#EC4899', description: 'Add colored borders or frames to your photos', metaTitle: 'Add Border to Image', metaDescription: 'Add custom borders to your pictures.', acceptedFormats: ['image/jpeg', 'image/png', 'image/webp'], maxFileSize: 20 * 1024 * 1024, multiFile: true, options: [
    { id: 'color', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], label: 'Border Color', type: 'color', defaultValue: '#000000' },
    { id: 'width', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], label: 'Border Width', type: 'slider', defaultValue: 10, min: 1, max: 100 }
  ], processor: 'border' },
  { id: 'pixelate-image', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], name: 'Pixelate Image', slug: 'pixelate-image', category: 'effects', icon: 'Grid', accentColor: '#EC4899', description: 'Censor or stylize images using pixelation', metaTitle: 'Pixelate Image Online', metaDescription: 'Pixelate your images quickly.', acceptedFormats: ['image/jpeg', 'image/png', 'image/webp'], maxFileSize: 20 * 1024 * 1024, multiFile: true, options: [
    { id: 'pixelSize', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], label: 'Pixel Size', type: 'slider', defaultValue: 10, min: 2, max: 100 }
  ], processor: 'filter', processorConfig: { type: 'pixelate' } },
  { id: 'pixelate-face', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], name: 'Pixelate Face', slug: 'pixelate-face', category: 'effects', icon: 'UserX', accentColor: '#EC4899', description: 'Automatically find and pixelate faces for privacy', metaTitle: 'Pixelate Faces Online', metaDescription: 'Censor faces in photos using pixelation.', acceptedFormats: ['image/jpeg', 'image/png', 'image/webp'], maxFileSize: 20 * 1024 * 1024, multiFile: false, options: [], processor: 'coming-soon', comingSoon: true },
  { id: 'censor-photo', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], name: 'Censor Photo', slug: 'censor-photo', category: 'effects', icon: 'Ban', accentColor: '#EC4899', description: 'Add black bars or blur to censor sensitive parts of a photo', metaTitle: 'Censor Photo Online', metaDescription: 'Easily censor sensitive information in photos.', acceptedFormats: ['image/jpeg', 'image/png', 'image/webp'], maxFileSize: 20 * 1024 * 1024, multiFile: false, options: [], processor: 'blur' },
  { id: 'motion-blur', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], name: 'Motion Blur', slug: 'motion-blur', category: 'effects', icon: 'Wind', accentColor: '#EC4899', description: 'Add a realistic directional motion blur effect', metaTitle: 'Add Motion Blur Online', metaDescription: 'Apply motion blur to images.', acceptedFormats: ['image/jpeg', 'image/png', 'image/webp'], maxFileSize: 20 * 1024 * 1024, multiFile: false, options: [
    { id: 'intensity', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], label: 'Intensity', type: 'slider', defaultValue: 20, min: 1, max: 100 },
    { id: 'angle', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], label: 'Angle', type: 'slider', defaultValue: 0, min: 0, max: 360 }
  ], processor: 'filter', processorConfig: { type: 'motion-blur' } },
  { id: 'grayscale', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], name: 'Grayscale', slug: 'grayscale-image', category: 'effects', icon: 'ImageMinus', accentColor: '#EC4899', description: 'Convert color photos to grayscale (B&W)', metaTitle: 'Convert Image to Grayscale', metaDescription: 'Make your images grayscale.', acceptedFormats: ['image/jpeg', 'image/png', 'image/webp'], maxFileSize: 20 * 1024 * 1024, multiFile: true, options: [], processor: 'filter', processorConfig: { filter: 'grayscale' } },
  { id: 'black-white', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], name: 'Black & White', slug: 'black-and-white-image', category: 'effects', icon: 'Contrast', accentColor: '#EC4899', description: 'Convert image to pure black and white without gray shades', metaTitle: 'Convert Image to Black and White', metaDescription: 'Apply a strict black and white filter.', acceptedFormats: ['image/jpeg', 'image/png', 'image/webp'], maxFileSize: 20 * 1024 * 1024, multiFile: true, options: [
    { id: 'threshold', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], label: 'Threshold', type: 'slider', defaultValue: 128, min: 0, max: 255 }
  ], processor: 'filter', processorConfig: { filter: 'threshold' } },
  { id: 'pixel-art', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], name: 'Picture to Pixel Art', slug: 'picture-to-pixel-art', category: 'effects', icon: 'Gamepad2', accentColor: '#EC4899', description: 'Transform standard photos into retro 8-bit style pixel art', metaTitle: 'Picture to Pixel Art Converter', metaDescription: 'Create 8-bit retro pixel art from your photos.', acceptedFormats: ['image/jpeg', 'image/png', 'image/webp'], maxFileSize: 20 * 1024 * 1024, multiFile: false, options: [], processor: 'filter', processorConfig: { type: 'pixelate' } },
  { id: 'add-white-border', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], name: 'Add White Border', slug: 'add-white-border', category: 'effects', icon: 'Frame', accentColor: '#EC4899', description: 'Add a clean white border for a polaroid or classic look', metaTitle: 'Add White Border to Photo', metaDescription: 'Quickly add a white border to photos.', acceptedFormats: ['image/jpeg', 'image/png', 'image/webp'], maxFileSize: 20 * 1024 * 1024, multiFile: true, options: [
    { id: 'width', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], label: 'Border Width', type: 'slider', defaultValue: 10, min: 1, max: 100 }
  ], processor: 'border', processorConfig: { color: '#ffffff' } },
  { id: 'ai-face-generator', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], name: 'AI Face Generator', slug: 'ai-face-generator', category: 'effects', icon: 'Bot', accentColor: '#EC4899', description: 'Generate realistic faces with AI', metaTitle: 'AI Face Generator', metaDescription: 'Generate human faces using AI.', acceptedFormats: [], maxFileSize: 0, multiFile: false, options: [], processor: 'coming-soon', comingSoon: true },
  { id: 'blemish-remover', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], name: 'Blemish Remover', slug: 'blemish-remover', category: 'effects', icon: 'Sparkle', accentColor: '#EC4899', description: 'Easily remove pimples, scars, and blemishes', metaTitle: 'Blemish Remover Online', metaDescription: 'Remove blemishes from faces automatically.', acceptedFormats: ['image/jpeg', 'image/png', 'image/webp'], maxFileSize: 20 * 1024 * 1024, multiFile: false, options: [], processor: 'coming-soon', comingSoon: true },
  { id: 'retouch-image', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], name: 'Retouch Image', slug: 'retouch-image', category: 'effects', icon: 'Brush', accentColor: '#EC4899', description: 'Retouch portraits and skin easily', metaTitle: 'Retouch Photo Online', metaDescription: 'Smooth skin and retouch portraits.', acceptedFormats: ['image/jpeg', 'image/png', 'image/webp'], maxFileSize: 20 * 1024 * 1024, multiFile: false, options: [], processor: 'coming-soon', comingSoon: true },
  { id: 'add-text', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], name: 'Add Text to Image', slug: 'add-text-to-image', category: 'effects', icon: 'Type', accentColor: '#EC4899', description: 'Overlay custom text and fonts onto your pictures', metaTitle: 'Add Text to Photo', metaDescription: 'Easily add custom text onto your images.', acceptedFormats: ['image/jpeg', 'image/png', 'image/webp'], maxFileSize: 20 * 1024 * 1024, multiFile: false, options: [
    { id: 'text', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], label: 'Text', type: 'text' as any, defaultValue: 'Your Text' }
  ], processor: 'text-overlay' },
  { id: 'add-logo', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], name: 'Add Logo to Image', slug: 'add-logo-to-image', category: 'effects', icon: 'Stamp', accentColor: '#EC4899', description: 'Watermark photos by adding your brand logo on top', metaTitle: 'Add Logo to Photo', metaDescription: 'Overlay your brand logo onto images.', acceptedFormats: ['image/jpeg', 'image/png', 'image/webp'], maxFileSize: 20 * 1024 * 1024, multiFile: false, options: [], processor: 'watermark' },

  // --- DPI & Quality ---
  { id: 'increase-image-quality', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], name: 'Increase Image Quality', slug: 'increase-image-quality', category: 'dpi-quality', icon: 'ArrowUpCircle', accentColor: '#14B8A6', description: 'Enhance low-resolution images without losing details', metaTitle: 'Increase Image Quality Online', metaDescription: 'Improve photo quality instantly.', acceptedFormats: ['image/jpeg', 'image/png', 'image/webp'], maxFileSize: 20 * 1024 * 1024, multiFile: false, options: [], processor: 'ai-enhance', comingSoon: true },
  { id: 'convert-dpi', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], name: 'Convert DPI', slug: 'convert-image-dpi', category: 'dpi-quality', icon: 'Printer', accentColor: '#14B8A6', description: 'Change DPI to 300, 600, or custom values for printing', metaTitle: 'Change Image DPI Online', metaDescription: 'Convert image DPI quickly for print requirements.', acceptedFormats: ['image/jpeg', 'image/png'], maxFileSize: 20 * 1024 * 1024, multiFile: true, options: [
    { id: 'dpi', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], label: 'Target DPI', type: 'select', defaultValue: '300', options: [{ label: '72 DPI', value: '72' }, { label: '300 DPI', value: '300' }, { label: '600 DPI', value: '600' }] }
  ], processor: 'metadata' },
  { id: 'check-dpi', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], name: 'Check Image DPI', slug: 'check-image-dpi', category: 'dpi-quality', icon: 'Search', accentColor: '#14B8A6', description: 'Instantly view the DPI and resolution metadata of any image', metaTitle: 'Check Image DPI Online', metaDescription: 'Find out the DPI of your image file.', acceptedFormats: ['image/jpeg', 'image/png'], maxFileSize: 20 * 1024 * 1024, multiFile: false, comingSoon: true, options: [], processor: 'metadata' },
  { id: 'super-resolution', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], name: 'Super Resolution', slug: 'super-resolution', category: 'dpi-quality', icon: 'ZoomIn', accentColor: '#14B8A6', description: 'Upscale your images 2x, 4x using AI super resolution', metaTitle: 'AI Image Upscaler', metaDescription: 'Upscale images up to 4x using AI.', acceptedFormats: ['image/jpeg', 'image/png', 'image/webp'], maxFileSize: 20 * 1024 * 1024, multiFile: false, options: [], processor: 'coming-soon', comingSoon: true },

  // --- Resize ---
  { id: 'resize-pixel', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], name: 'Resize by Pixel', slug: 'resize-image-by-pixel', category: 'resize', icon: 'Maximize', accentColor: '#F59E0B', description: 'Resize images to exact pixel dimensions (width x height)', metaTitle: 'Resize Image in Pixels', metaDescription: 'Resize photos to custom pixel sizes.', acceptedFormats: ['image/jpeg', 'image/png', 'image/webp'], maxFileSize: 20 * 1024 * 1024, multiFile: true, options: [
    { id: 'width', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], label: 'Width (px)', type: 'number', defaultValue: 1080 },
    { id: 'height', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], label: 'Height (px)', type: 'number', defaultValue: 1080 }
  ], processor: 'resize', processorConfig: { unit: 'px' } },
  { id: 'resize-cm', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], name: 'Resize in Centimeters', slug: 'resize-image-in-cm', category: 'resize', icon: 'Ruler', accentColor: '#F59E0B', description: 'Resize images to exact cm measurements for print', metaTitle: 'Resize Image in CM', metaDescription: 'Resize photos based on centimeter dimensions.', acceptedFormats: ['image/jpeg', 'image/png', 'image/webp'], maxFileSize: 20 * 1024 * 1024, multiFile: true, options: [
    { id: 'width', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], label: 'Width (cm)', type: 'number', defaultValue: 10 },
    { id: 'height', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], label: 'Height (cm)', type: 'number', defaultValue: 15 },
    { id: 'dpi', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], label: 'DPI', type: 'number', defaultValue: 300 }
  ], processor: 'resize', processorConfig: { unit: 'cm' } },
  { id: 'resize-mm', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], name: 'Resize in Millimeters', slug: 'resize-image-in-mm', category: 'resize', icon: 'Ruler', accentColor: '#F59E0B', description: 'Resize images to exact mm dimensions', metaTitle: 'Resize Image in MM', metaDescription: 'Resize photos based on millimeter dimensions.', acceptedFormats: ['image/jpeg', 'image/png', 'image/webp'], maxFileSize: 20 * 1024 * 1024, multiFile: true, options: [
    { id: 'width', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], label: 'Width (mm)', type: 'number', defaultValue: 100 },
    { id: 'height', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], label: 'Height (mm)', type: 'number', defaultValue: 150 },
    { id: 'dpi', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], label: 'DPI', type: 'number', defaultValue: 300 }
  ], processor: 'resize', processorConfig: { unit: 'mm' } },
  { id: 'resize-inches', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], name: 'Resize in Inches', slug: 'resize-image-in-inches', category: 'resize', icon: 'Ruler', accentColor: '#F59E0B', description: 'Resize images to exact inch sizes for standard framing', metaTitle: 'Resize Image in Inches', metaDescription: 'Resize photos based on inches.', acceptedFormats: ['image/jpeg', 'image/png', 'image/webp'], maxFileSize: 20 * 1024 * 1024, multiFile: true, options: [
    { id: 'width', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], label: 'Width (in)', type: 'number', defaultValue: 4 },
    { id: 'height', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], label: 'Height (in)', type: 'number', defaultValue: 6 },
    { id: 'dpi', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], label: 'DPI', type: 'number', defaultValue: 300 }
  ], processor: 'resize', processorConfig: { unit: 'in' } },
  { id: 'bulk-resize', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], name: 'Bulk Image Resizer', slug: 'bulk-image-resizer', category: 'resize', icon: 'Copy', accentColor: '#F59E0B', description: 'Resize multiple images at once to the same size', metaTitle: 'Bulk Image Resizer', metaDescription: 'Batch resize hundreds of images instantly.', acceptedFormats: ['image/jpeg', 'image/png', 'image/webp'], maxFileSize: 50 * 1024 * 1024, multiFile: true, options: [
    { id: 'width', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], label: 'Width (px)', type: 'number', defaultValue: 800 },
    { id: 'height', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], label: 'Height (px)', type: 'number', defaultValue: 800 }
  ], processor: 'resize', processorConfig: { unit: 'px' } },
  { id: 'upscale-ai', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], name: 'Upscale Image with AI', slug: 'upscale-image-ai', category: 'resize', icon: 'Sparkles', accentColor: '#F59E0B', description: 'Upscale small pictures to high resolution using AI models', metaTitle: 'AI Image Upscaler', metaDescription: 'Enlarge images without losing quality.', acceptedFormats: ['image/jpeg', 'image/png', 'image/webp'], maxFileSize: 20 * 1024 * 1024, multiFile: false, options: [], processor: 'coming-soon', comingSoon: true },

  // --- Official Sizes ---
  { id: 'size-a4', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], name: 'A4', slug: 'a4-image-size', category: 'official-sizes', icon: 'File', accentColor: '#8B5CF6', description: 'Resize image precisely to A4 standard dimensions', metaTitle: 'Resize to A4 Size', metaDescription: 'Resize image to fit A4 paper exactly.', acceptedFormats: ['image/jpeg', 'image/png', 'image/webp'], maxFileSize: 20 * 1024 * 1024, multiFile: true, options: [], processor: 'resize', processorConfig: { width: 2480, height: 3508 } },
  { id: 'size-ssc', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], name: 'SSC Photo', slug: 'ssc-photo-size', category: 'official-sizes', icon: 'User', accentColor: '#8B5CF6', description: 'Resize photo and signature for SSC application forms', metaTitle: 'SSC Photo Maker', metaDescription: 'Create photos valid for SSC forms.', acceptedFormats: ['image/jpeg'], maxFileSize: 10 * 1024 * 1024, multiFile: false, options: [{ id: 'size', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], label: 'Size', type: 'select', defaultValue: '35x45mm', options: [{ label: '35x45 mm (Europe/UK)', value: '35x45mm' }, { label: '2x2 inch (US)', value: '2x2in' }] }, { id: 'bgColor', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], label: 'Background Color', type: 'color', defaultValue: '#ffffff' }, { id: 'printSheet', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], label: 'Print Sheet', type: 'select', defaultValue: 'none', options: [{ label: 'None (Single Photo)', value: 'none' }, { label: 'A4 Sheet', value: 'a4' }, { label: '4x6 Sheet', value: '4x6' }] }], processor: 'passport' },
  { id: 'size-pan', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], name: 'PAN Card', slug: 'pan-card-photo-size', category: 'official-sizes', icon: 'CreditCard', accentColor: '#8B5CF6', description: 'Format your photo and signature for NSDL PAN card applications', metaTitle: 'PAN Card Photo Resizer', metaDescription: 'Generate valid PAN card application photos.', acceptedFormats: ['image/jpeg'], maxFileSize: 10 * 1024 * 1024, multiFile: false, options: [{ id: 'size', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], label: 'Size', type: 'select', defaultValue: '35x45mm', options: [{ label: '35x45 mm (Europe/UK)', value: '35x45mm' }, { label: '2x2 inch (US)', value: '2x2in' }] }, { id: 'bgColor', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], label: 'Background Color', type: 'color', defaultValue: '#ffffff' }, { id: 'printSheet', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], label: 'Print Sheet', type: 'select', defaultValue: 'none', options: [{ label: 'None (Single Photo)', value: 'none' }, { label: 'A4 Sheet', value: 'a4' }, { label: '4x6 Sheet', value: '4x6' }] }], processor: 'passport' },
  { id: 'size-upsc', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], name: 'UPSC Photo', slug: 'upsc-photo-size', category: 'official-sizes', icon: 'Landmark', accentColor: '#8B5CF6', description: 'Create photos according to strict UPSC guidelines', metaTitle: 'UPSC Photo Maker', metaDescription: 'Create photos valid for UPSC forms.', acceptedFormats: ['image/jpeg'], maxFileSize: 10 * 1024 * 1024, multiFile: false, options: [{ id: 'size', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], label: 'Size', type: 'select', defaultValue: '35x45mm', options: [{ label: '35x45 mm (Europe/UK)', value: '35x45mm' }, { label: '2x2 inch (US)', value: '2x2in' }] }, { id: 'bgColor', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], label: 'Background Color', type: 'color', defaultValue: '#ffffff' }, { id: 'printSheet', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], label: 'Print Sheet', type: 'select', defaultValue: 'none', options: [{ label: 'None (Single Photo)', value: 'none' }, { label: 'A4 Sheet', value: 'a4' }, { label: '4x6 Sheet', value: '4x6' }] }], processor: 'passport' },
  { id: 'size-psc', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], name: 'PSC Photo', slug: 'psc-photo-size', category: 'official-sizes', icon: 'Briefcase', accentColor: '#8B5CF6', description: 'Format photos for various state Public Service Commission exams', metaTitle: 'PSC Photo Resizer', metaDescription: 'Format photos for PSC applications.', acceptedFormats: ['image/jpeg'], maxFileSize: 10 * 1024 * 1024, multiFile: false, options: [{ id: 'size', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], label: 'Size', type: 'select', defaultValue: '35x45mm', options: [{ label: '35x45 mm (Europe/UK)', value: '35x45mm' }, { label: '2x2 inch (US)', value: '2x2in' }] }, { id: 'bgColor', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], label: 'Background Color', type: 'color', defaultValue: '#ffffff' }, { id: 'printSheet', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], label: 'Print Sheet', type: 'select', defaultValue: 'none', options: [{ label: 'None (Single Photo)', value: 'none' }, { label: 'A4 Sheet', value: 'a4' }, { label: '4x6 Sheet', value: '4x6' }] }], processor: 'passport' },

  // --- Passport & ID ---
  { id: 'passport-maker', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], name: 'Passport Photo Maker', slug: 'passport-photo-maker', category: 'passport-id', icon: 'Camera', accentColor: '#06B6D4', description: 'Create standard passport photos from any portrait', metaTitle: 'Online Passport Photo Maker', metaDescription: 'Create passport photos easily.', acceptedFormats: ['image/jpeg', 'image/png'], maxFileSize: 20 * 1024 * 1024, multiFile: false, options: [{ id: 'size', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], label: 'Size', type: 'select', defaultValue: '35x45mm', options: [{ label: '35x45 mm (Europe/UK)', value: '35x45mm' }, { label: '2x2 inch (US)', value: '2x2in' }] }, { id: 'bgColor', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], label: 'Background Color', type: 'color', defaultValue: '#ffffff' }, { id: 'printSheet', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], label: 'Print Sheet', type: 'select', defaultValue: 'none', options: [{ label: 'None (Single Photo)', value: 'none' }, { label: 'A4 Sheet', value: 'a4' }, { label: '4x6 Sheet', value: '4x6' }] }], processor: 'passport' },
  { id: 'passport-red', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], name: 'Red Background Passport', slug: 'red-background-passport', category: 'passport-id', icon: 'UserSquare', accentColor: '#06B6D4', description: 'Change passport background to official red', metaTitle: 'Red Background Passport Photo', metaDescription: 'Create red background passport photos.', acceptedFormats: ['image/jpeg', 'image/png'], maxFileSize: 20 * 1024 * 1024, multiFile: false, options: [], processor: 'coming-soon', comingSoon: true },
  { id: 'passport-white', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], name: 'White Background Passport', slug: 'white-background-passport', category: 'passport-id', icon: 'UserSquare', accentColor: '#06B6D4', description: 'Change passport background to official white', metaTitle: 'White Background Passport Photo', metaDescription: 'Create white background passport photos.', acceptedFormats: ['image/jpeg', 'image/png'], maxFileSize: 20 * 1024 * 1024, multiFile: false, options: [], processor: 'coming-soon', comingSoon: true },
  { id: 'sig-6x2', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], name: 'Signature 6cm x 2cm', slug: 'signature-6cm-x-2cm', category: 'passport-id', icon: 'PenTool', accentColor: '#06B6D4', description: 'Resize signature to 6x2 cm', metaTitle: 'Resize Signature to 6x2 cm', metaDescription: 'Crop and resize signature to 6x2 cm.', acceptedFormats: ['image/jpeg', 'image/png'], maxFileSize: 10 * 1024 * 1024, multiFile: false, options: [], processor: 'resize', processorConfig: { unit: 'cm', width: 6, height: 2 } },
  { id: 'photo-35x45', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], name: '3.5cm x 4.5cm', slug: 'photo-3-5cm-x-4-5cm', category: 'passport-id', icon: 'Crop', accentColor: '#06B6D4', description: 'Standard Europe and UK passport photo size', metaTitle: '3.5x4.5 cm Photo Maker', metaDescription: 'Resize photo to 3.5x4.5 cm.', acceptedFormats: ['image/jpeg', 'image/png'], maxFileSize: 10 * 1024 * 1024, multiFile: false, options: [], processor: 'resize', processorConfig: { unit: 'cm', width: 3.5, height: 4.5 } },
  { id: 'sig-50x20', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], name: 'Signature 50mm x 20mm', slug: 'signature-50mm-x-20mm', category: 'passport-id', icon: 'PenTool', accentColor: '#06B6D4', description: 'Resize signature image to 50x20 mm', metaTitle: 'Resize Signature to 50x20 mm', metaDescription: 'Format signature for forms to 50x20 mm.', acceptedFormats: ['image/jpeg', 'image/png'], maxFileSize: 10 * 1024 * 1024, multiFile: false, options: [], processor: 'resize', processorConfig: { unit: 'cm' } },
  { id: 'photo-35mm-45mm', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], name: '35mm x 45mm', slug: 'photo-35mm-x-45mm', category: 'passport-id', icon: 'Crop', accentColor: '#06B6D4', description: 'Resize photo strictly to 35x45 mm', metaTitle: '35x45 mm Photo Maker', metaDescription: 'Create 35x45 mm photos.', acceptedFormats: ['image/jpeg', 'image/png'], maxFileSize: 10 * 1024 * 1024, multiFile: false, options: [], processor: 'resize', processorConfig: { unit: 'cm' } },
  { id: 'photo-2x2', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], name: '2x2 inch', slug: 'photo-2x2-inch', category: 'passport-id', icon: 'Square', accentColor: '#06B6D4', description: 'Standard US passport and visa photo size', metaTitle: '2x2 inch Photo Maker', metaDescription: 'Create 2x2 inch photos.', acceptedFormats: ['image/jpeg', 'image/png'], maxFileSize: 10 * 1024 * 1024, multiFile: false, options: [], processor: 'resize', processorConfig: { unit: 'cm' } },
  { id: 'photo-3x4', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], name: '3x4 inch', slug: 'photo-3x4-inch', category: 'passport-id', icon: 'Maximize', accentColor: '#06B6D4', description: 'Standard 3x4 inch photo print size', metaTitle: '3x4 inch Photo Maker', metaDescription: 'Create 3x4 inch photos.', acceptedFormats: ['image/jpeg', 'image/png'], maxFileSize: 10 * 1024 * 1024, multiFile: false, options: [], processor: 'resize', processorConfig: { unit: 'cm' } },
  { id: 'photo-4x6', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], name: '4x6 inch', slug: 'photo-4x6-inch', category: 'passport-id', icon: 'Maximize', accentColor: '#06B6D4', description: 'Standard 4x6 inch photo print size', metaTitle: '4x6 inch Photo Maker', metaDescription: 'Create 4x6 inch photos.', acceptedFormats: ['image/jpeg', 'image/png'], maxFileSize: 10 * 1024 * 1024, multiFile: false, options: [], processor: 'resize', processorConfig: { unit: 'cm' } },
  { id: 'photo-600x600', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], name: '600x600 px', slug: 'photo-600x600-px', category: 'passport-id', icon: 'Square', accentColor: '#06B6D4', description: 'US visa digital photo requirement (600x600 pixels)', metaTitle: '600x600 px Photo Maker', metaDescription: 'Resize image to 600x600 px.', acceptedFormats: ['image/jpeg', 'image/png'], maxFileSize: 10 * 1024 * 1024, multiFile: false, options: [], processor: 'resize', processorConfig: { width: 600, height: 600 } },

  // --- Social Media ---
  { id: 'ig-nocrop', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], name: 'Instagram No Crop', slug: 'instagram-no-crop', category: 'social-media', icon: 'Instagram', accentColor: '#F43F5E', description: 'Fit whole pictures on Instagram without cropping', metaTitle: 'Fit Image to Instagram No Crop', metaDescription: 'Post full images to Instagram.', acceptedFormats: ['image/jpeg', 'image/png', 'image/webp'], maxFileSize: 20 * 1024 * 1024, multiFile: false, options: [], processor: 'border' },
  { id: 'ig-grid', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], name: 'Instagram Grid Maker', slug: 'instagram-grid-maker', category: 'social-media', icon: 'Grid', accentColor: '#F43F5E', description: 'Split an image into 3x1, 3x2, or 3x3 grids for IG profile', metaTitle: 'Instagram Grid Maker', metaDescription: 'Create grid posts for Instagram.', acceptedFormats: ['image/jpeg', 'image/png', 'image/webp'], maxFileSize: 20 * 1024 * 1024, multiFile: false, options: [], processor: 'split' },
  { id: 'wa-dp', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], name: 'WhatsApp DP', slug: 'whatsapp-dp-without-crop', category: 'social-media', icon: 'MessageCircle', accentColor: '#F43F5E', description: 'Create a full WhatsApp profile picture without cropping', metaTitle: 'WhatsApp DP Maker', metaDescription: 'Set WhatsApp DP without cropping.', acceptedFormats: ['image/jpeg', 'image/png', 'image/webp'], maxFileSize: 20 * 1024 * 1024, multiFile: false, options: [], processor: 'border' },
  { id: 'yt-banner', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], name: 'YouTube Banner', slug: 'youtube-banner-maker', category: 'social-media', icon: 'Youtube', accentColor: '#F43F5E', description: 'Resize and crop images to fit YouTube banner dimensions exactly', metaTitle: 'YouTube Banner Maker', metaDescription: 'Create perfectly sized YouTube banners.', acceptedFormats: ['image/jpeg', 'image/png', 'image/webp'], maxFileSize: 20 * 1024 * 1024, multiFile: false, options: [], processor: 'resize', processorConfig: { width: 2560, height: 1440 } },
  { id: 'zoom-out', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], name: 'Zoom Out Image', slug: 'zoom-out-image', category: 'social-media', icon: 'ZoomOut', accentColor: '#F43F5E', description: 'Add padding and zoom out your photo for a better fit', metaTitle: 'Zoom Out Image', metaDescription: 'Add padding to your photos.', acceptedFormats: ['image/jpeg', 'image/png', 'image/webp'], maxFileSize: 20 * 1024 * 1024, multiFile: false, options: [], processor: 'border' },

  // --- Conversions ---
  { id: 'image-converter', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], name: 'Image Converter', slug: 'image-converter', category: 'conversions', icon: 'RefreshCcw', accentColor: '#10B981', description: 'Convert between any image formats', metaTitle: 'Universal Image Converter', metaDescription: 'Convert images to JPG, PNG, WEBP and more.', acceptedFormats: ['image/jpeg', 'image/png', 'image/webp', 'image/gif', 'image/bmp'], maxFileSize: 50 * 1024 * 1024, multiFile: true, options: [
    { id: 'format', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], label: 'Target Format', type: 'select', defaultValue: 'image/jpeg', options: [{ label: 'JPG', value: 'image/jpeg' }, { label: 'PNG', value: 'image/png' }, { label: 'WEBP', value: 'image/webp' }] }
  ], processor: 'convert' },
  { id: 'img-to-jpg', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], name: 'Image to JPG', slug: 'image-to-jpg', category: 'conversions', icon: 'FileImage', accentColor: '#10B981', description: 'Convert any image type to standard JPG format', metaTitle: 'Convert Image to JPG', metaDescription: 'Easily convert images to JPG format.', acceptedFormats: ['image/png', 'image/webp', 'image/gif', 'image/bmp'], maxFileSize: 50 * 1024 * 1024, multiFile: true, options: [], processor: 'convert', processorConfig: { format: 'image/jpeg' } },
  { id: 'jpeg-to-jpg', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], name: 'JPEG to JPG', slug: 'jpeg-to-jpg', category: 'conversions', icon: 'FileImage', accentColor: '#10B981', description: 'Standardize .jpeg extensions to .jpg', metaTitle: 'Convert JPEG to JPG', metaDescription: 'Rename and standardize JPEG to JPG.', acceptedFormats: ['image/jpeg'], maxFileSize: 50 * 1024 * 1024, multiFile: true, options: [], processor: 'convert', processorConfig: { format: 'image/jpeg' } },
  { id: 'heic-to-jpg', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], name: 'HEIC to JPG', slug: 'heic-to-jpg', category: 'conversions', icon: 'Smartphone', accentColor: '#10B981', description: 'Convert Apple HEIC photos to universal JPG', metaTitle: 'Convert HEIC to JPG', metaDescription: 'Convert iPhone photos to JPG format.', acceptedFormats: ['image/heic', 'image/heif'], maxFileSize: 50 * 1024 * 1024, multiFile: true, options: [], processor: 'convert', processorConfig: { format: 'image/jpeg' } },
  { id: 'webp-to-jpg', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], name: 'WEBP to JPG', slug: 'webp-to-jpg', category: 'conversions', icon: 'FileImage', accentColor: '#10B981', description: 'Convert WEBP web images to standard JPG', metaTitle: 'Convert WEBP to JPG', metaDescription: 'Convert WebP images to JPG format.', acceptedFormats: ['image/webp'], maxFileSize: 50 * 1024 * 1024, multiFile: true, options: [], processor: 'convert', processorConfig: { format: 'image/jpeg' } },
  { id: 'webp-to-png', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], name: 'WebP to PNG', slug: 'webp-to-png', category: 'conversions', icon: 'FileImage', accentColor: '#10B981', description: 'Convert WEBP to transparent PNG', metaTitle: 'Convert WebP to PNG', metaDescription: 'Convert WebP to PNG retaining transparency.', acceptedFormats: ['image/webp'], maxFileSize: 50 * 1024 * 1024, multiFile: true, options: [], processor: 'convert', processorConfig: { format: 'image/png' } },
  { id: 'avif-to-jpg', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], name: 'AVIF to JPG', slug: 'avif-to-jpg', category: 'conversions', icon: 'FileImage', accentColor: '#10B981', description: 'Convert next-gen AVIF images to standard JPG', metaTitle: 'Convert AVIF to JPG', metaDescription: 'Convert AVIF images to JPG.', acceptedFormats: ['image/avif'], maxFileSize: 50 * 1024 * 1024, multiFile: true, options: [], processor: 'convert', processorConfig: { format: 'image/jpeg' } },
  { id: 'jfif-to-jpg', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], name: 'JFIF to JPG', slug: 'jfif-to-jpg', category: 'conversions', icon: 'FileImage', accentColor: '#10B981', description: 'Convert JFIF files to standard JPG', metaTitle: 'Convert JFIF to JPG', metaDescription: 'Fix and convert JFIF files to JPG.', acceptedFormats: ['image/jfif', 'image/jpeg'], maxFileSize: 50 * 1024 * 1024, multiFile: true, options: [], processor: 'convert', processorConfig: { format: 'image/jpeg' } },
  { id: 'jpeg-to-png', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], name: 'JPEG to PNG', slug: 'jpeg-to-png', category: 'conversions', icon: 'FileImage', accentColor: '#10B981', description: 'Convert JPEG photos to lossless PNG format', metaTitle: 'Convert JPEG to PNG', metaDescription: 'Convert JPEG to PNG format.', acceptedFormats: ['image/jpeg'], maxFileSize: 50 * 1024 * 1024, multiFile: true, options: [], processor: 'convert', processorConfig: { format: 'image/png' } },
  { id: 'png-to-jpeg', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], name: 'PNG to JPEG', slug: 'png-to-jpeg', category: 'conversions', icon: 'FileImage', accentColor: '#10B981', description: 'Convert heavy PNGs into lighter JPEG files', metaTitle: 'Convert PNG to JPEG', metaDescription: 'Compress PNG files by converting to JPEG.', acceptedFormats: ['image/png'], maxFileSize: 50 * 1024 * 1024, multiFile: true, options: [], processor: 'convert', processorConfig: { format: 'image/jpeg' } },
  { id: 'png-to-ico', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], name: 'PNG to ICO', slug: 'png-to-ico', category: 'conversions', icon: 'Layout', accentColor: '#10B981', description: 'Convert PNG logos into ICO format for website favicons', metaTitle: 'Convert PNG to ICO', metaDescription: 'Create favicon ICO files from PNG.', acceptedFormats: ['image/png'], maxFileSize: 10 * 1024 * 1024, multiFile: true, options: [], processor: 'convert', processorConfig: { format: 'image/x-icon' } },
  { id: 'img-to-word', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], name: 'Image to Word', slug: 'image-to-word', category: 'conversions', icon: 'FileText', accentColor: '#10B981', description: 'Extract text and layout from an image into a Word document', metaTitle: 'Convert Image to Word', metaDescription: 'Extract text from image to DOCX.', acceptedFormats: ['image/jpeg', 'image/png', 'image/webp'], maxFileSize: 20 * 1024 * 1024, multiFile: false, options: [], processor: 'ocr', comingSoon: true },
  { id: 'jpg-to-text', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], name: 'JPG to Text', slug: 'jpg-to-text', category: 'conversions', icon: 'Type', accentColor: '#10B981', description: 'Extract plain text from a JPG using OCR', metaTitle: 'Extract Text from JPG', metaDescription: 'JPG to Text OCR tool.', acceptedFormats: ['image/jpeg'], maxFileSize: 20 * 1024 * 1024, multiFile: false, options: [], processor: 'ocr', comingSoon: true },
  { id: 'png-to-text', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], name: 'PNG to Text', slug: 'png-to-text', category: 'conversions', icon: 'Type', accentColor: '#10B981', description: 'Extract plain text from a PNG using OCR', metaTitle: 'Extract Text from PNG', metaDescription: 'PNG to Text OCR tool.', acceptedFormats: ['image/png'], maxFileSize: 20 * 1024 * 1024, multiFile: false, options: [], processor: 'ocr', comingSoon: true },
  { id: 'favicon-gen', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], name: 'Favicon Generator', slug: 'favicon-generator', category: 'conversions', icon: 'Globe', accentColor: '#10B981', description: 'Generate a complete favicon package from any image', metaTitle: 'Free Favicon Generator', metaDescription: 'Generate favicons for your website.', acceptedFormats: ['image/jpeg', 'image/png', 'image/webp'], maxFileSize: 10 * 1024 * 1024, multiFile: false, options: [], processor: 'coming-soon', comingSoon: true },

  // --- Image to PDF ---
  { id: 'img-to-pdf', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], name: 'Image to PDF', slug: 'image-to-pdf', category: 'image-to-pdf', icon: 'FileText', accentColor: '#EF4444', description: 'Combine multiple images into a single PDF document', metaTitle: 'Convert Images to PDF', metaDescription: 'Convert JPG/PNG to PDF format.', acceptedFormats: ['image/jpeg', 'image/png', 'image/webp'], maxFileSize: 50 * 1024 * 1024, multiFile: true, options: [], processor: 'image-to-pdf' },
  { id: 'pdf-to-jpg', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], name: 'PDF to JPG', slug: 'pdf-to-jpg', category: 'image-to-pdf', icon: 'Images', accentColor: '#EF4444', description: 'Extract pages from a PDF as separate JPG images', metaTitle: 'Convert PDF to JPG', metaDescription: 'Extract images from PDF files.', acceptedFormats: ['application/pdf'], maxFileSize: 50 * 1024 * 1024, multiFile: false, options: [], processor: 'pdf-to-image' },
  // Let's loop these for compactness, but explicitly defined as requested
  ...([50, 100, 150, 200, 250, 300, 400, 500, 1000, 2000].map(size => {
    const isMB = size >= 1000;
    const sizeStr = isMB ? `${size / 1000}MB` : `${size}KB`;
    return {
      id: `jpg-to-pdf-${size}`,
      name: `JPG to PDF under ${sizeStr}`,
      slug: `jpg-to-pdf-under-${sizeStr.toLowerCase()}`,
      category: 'image-to-pdf' as CategoryId,
      icon: 'FileText',
      accentColor: '#EF4444',
      description: `Convert JPG to PDF and compress under ${sizeStr}`,
      metaTitle: `JPG to PDF under ${sizeStr}`,
      metaDescription: `Compress and convert JPG to PDF under ${sizeStr}.`,
      acceptedFormats: ['image/jpeg'],
      maxFileSize: 50 * 1024 * 1024,
      multiFile: true,
      options: [],
      processor: 'image-to-pdf' as ProcessorType,
      processorConfig: { targetSizeKB: size }
    };
  })),

  // --- Compression ---
  { id: 'image-compressor', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], name: 'Image Compressor', slug: 'image-compressor', category: 'compression', icon: 'Minimize', accentColor: '#4449A6', description: 'Compress images intelligently while keeping quality', metaTitle: 'Online Image Compressor', metaDescription: 'Compress images without losing quality.', acceptedFormats: ['image/jpeg', 'image/png', 'image/webp'], maxFileSize: 50 * 1024 * 1024, multiFile: true, options: [
    { id: 'targetSizeKB', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], label: 'Exact Target Size (KB)', type: 'number', defaultValue: 0, description: 'Enter exact KB (e.g. 250) or leave as 0 to use Quality slider instead.' },
    { id: 'quality', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], label: 'Or Adjust Quality', type: 'slider', defaultValue: 80, min: 1, max: 100 }
  ], processor: 'compress' },
  { id: 'reduce-kb', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], name: 'Reduce Size in KB', slug: 'reduce-image-size-in-kb', category: 'compression', icon: 'ArrowDownToLine', accentColor: '#4449A6', description: 'Target a specific kilobyte size for your image', metaTitle: 'Reduce Image Size in KB', metaDescription: 'Compress images to exact KB size.', acceptedFormats: ['image/jpeg', 'image/png', 'image/webp'], maxFileSize: 50 * 1024 * 1024, multiFile: true, options: [
    { id: 'targetKB', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], label: 'Target Size (KB)', type: 'number', defaultValue: 100 }
  ], processor: 'compress' },
  { id: 'reduce-mb', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], name: 'Reduce Size in MB', slug: 'reduce-image-size-in-mb', category: 'compression', icon: 'ArrowDownToLine', accentColor: '#4449A6', description: 'Target a specific megabyte size for your image', metaTitle: 'Reduce Image Size in MB', metaDescription: 'Compress images to exact MB size.', acceptedFormats: ['image/jpeg', 'image/png', 'image/webp'], maxFileSize: 100 * 1024 * 1024, multiFile: true, options: [
    { id: 'targetMB', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], label: 'Target Size (MB)', type: 'number', defaultValue: 1 }
  ], processor: 'compress' },
  { id: 'jpg-to-kb', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], name: 'JPG to KB', slug: 'jpg-to-kb', category: 'compression', icon: 'FileImage', accentColor: '#4449A6', description: 'Compress JPG files down to a small KB footprint', metaTitle: 'Compress JPG to KB', metaDescription: 'Reduce JPG file size to KB.', acceptedFormats: ['image/jpeg'], maxFileSize: 50 * 1024 * 1024, multiFile: true, options: [
    { id: 'targetKB', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], label: 'Target Size (KB)', type: 'number', defaultValue: 50 }
  ], processor: 'compress' },
  { id: 'mb-to-kb', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], name: 'MB to KB', slug: 'mb-to-kb-image-converter', category: 'compression', icon: 'ArrowDownRight', accentColor: '#4449A6', description: 'Shrink large MB pictures down to KB', metaTitle: 'Convert MB to KB', metaDescription: 'Compress large MB images to KB.', acceptedFormats: ['image/jpeg', 'image/png', 'image/webp'], maxFileSize: 100 * 1024 * 1024, multiFile: true, options: [
    { id: 'targetKB', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], label: 'Target Size (KB)', type: 'number', defaultValue: 500 }
  ], processor: 'compress' },
  { id: 'kb-to-mb', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], name: 'KB to MB', slug: 'kb-to-mb', category: 'compression', icon: 'ArrowUpRight', accentColor: '#4449A6', description: 'Increase image file size from KB to MB without altering dimensions', metaTitle: 'Increase KB to MB', metaDescription: 'Pad and increase image file size.', acceptedFormats: ['image/jpeg', 'image/png'], maxFileSize: 50 * 1024 * 1024, multiFile: true, options: [
    { id: 'targetMB', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], label: 'Target Size (MB)', type: 'number', defaultValue: 1 }
  ], processor: 'coming-soon', comingSoon: true },

  // --- Exact Target Sizes ---
  ...([5, 10, 15, 20, 25, 30, 40, 50, 60, 70, 80, 90, 100, 150, 200, 300, 500, 1000, 2000].map(size => {
    const isMB = size >= 1000;
    const sizeStr = isMB ? `${size / 1000}MB` : `${size}KB`;
    return {
      id: `compress-${size}`,
      name: `Compress to ${sizeStr}`,
      slug: `compress-image-to-${sizeStr.toLowerCase()}`,
      category: 'exact-size' as CategoryId,
      icon: 'Target',
      accentColor: '#7C3AED',
      description: `Compress your image to exactly ${sizeStr}`,
      metaTitle: `Compress Image to ${sizeStr}`,
      metaDescription: `Reduce your image size to exactly ${sizeStr} instantly.`,
      acceptedFormats: ['image/jpeg', 'image/png', 'image/webp'],
      maxFileSize: 50 * 1024 * 1024,
      multiFile: true,
      options: [],
      processor: 'compress' as ProcessorType,
      processorConfig: { targetSizeKB: size }
    };
  })),

  // --- PDF Tools ---
  { id: 'merge-pdf', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], name: 'Merge PDF', slug: 'merge-pdf', category: 'pdf-tools', icon: 'Files', accentColor: '#DC2626', description: 'Combine multiple PDF files into one single document', metaTitle: 'Merge PDF Online', metaDescription: 'Combine PDF files easily.', acceptedFormats: ['application/pdf'], maxFileSize: 50 * 1024 * 1024, multiFile: true, options: [], processor: 'coming-soon', comingSoon: true },
  ...([50, 100, 200, 500].map(size => ({
    id: `compress-pdf-${size}`,
    name: `Compress PDF to ${size}KB`,
    slug: `compress-pdf-to-${size}kb`,
    category: 'pdf-tools' as CategoryId,
    icon: 'Minimize2',
    accentColor: '#DC2626',
    description: `Reduce PDF file size to exactly ${size}KB`,
    metaTitle: `Compress PDF to ${size}KB`,
    metaDescription: `Compress your PDF files to ${size}KB securely.`,
    acceptedFormats: ['application/pdf'],
    maxFileSize: 50 * 1024 * 1024,
    multiFile: true,
    options: [],
    processor: 'coming-soon' as ProcessorType,
    comingSoon: true
  }))),
  { id: 'increase-pdf-size', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], name: 'Increase PDF Size', slug: 'increase-pdf-size', category: 'pdf-tools', icon: 'Maximize2', accentColor: '#DC2626', description: 'Pad and increase PDF file size to meet minimum limits', metaTitle: 'Increase PDF File Size', metaDescription: 'Make your PDF file size larger.', acceptedFormats: ['application/pdf'], maxFileSize: 50 * 1024 * 1024, multiFile: false, options: [], processor: 'coming-soon', comingSoon: true },
  { id: 'pdf-to-images', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], name: 'PDF to Images', slug: 'pdf-to-images', category: 'pdf-tools', icon: 'Images', accentColor: '#DC2626', description: 'Convert all pages of a PDF to separate images', metaTitle: 'Convert PDF to Images', metaDescription: 'Extract all pages of a PDF into images.', acceptedFormats: ['application/pdf'], maxFileSize: 50 * 1024 * 1024, multiFile: false, options: [], processor: 'pdf-to-image' },

  // --- GIF Tools ---
  { id: 'gif-maker', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], name: 'GIF Maker', slug: 'gif-maker', category: 'gif-tools', icon: 'Film', accentColor: '#059669', description: 'Create an animated GIF from a sequence of images', metaTitle: 'Animated GIF Maker', metaDescription: 'Create GIFs from images.', acceptedFormats: ['image/jpeg', 'image/png', 'image/webp'], maxFileSize: 50 * 1024 * 1024, multiFile: true, options: [
    { id: 'delay', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], label: 'Delay (ms)', type: 'slider', defaultValue: 500, min: 100, max: 2000 }
  ], processor: 'gif' },
  { id: 'gif-compressor', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], name: 'GIF Compressor', slug: 'compress-gif', category: 'gif-tools', icon: 'Minimize', accentColor: '#059669', description: 'Reduce the file size of heavy animated GIFs', metaTitle: 'Compress GIF Online', metaDescription: 'Reduce GIF file size easily.', acceptedFormats: ['image/gif'], maxFileSize: 50 * 1024 * 1024, multiFile: true, options: [
    { id: 'level', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], label: 'Compression Level', type: 'slider', defaultValue: 50, min: 1, max: 100 }
  ], processor: 'gif' },
  { id: 'add-text-gif', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], name: 'Add Text to GIF', slug: 'add-text-to-gif', category: 'gif-tools', icon: 'Type', accentColor: '#059669', description: 'Overlay captions and text onto animated GIFs', metaTitle: 'Add Text to GIF', metaDescription: 'Add moving text to your GIFs.', acceptedFormats: ['image/gif'], maxFileSize: 50 * 1024 * 1024, multiFile: false, options: [
    { id: 'text', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], label: 'Text', type: 'text' as any, defaultValue: 'Your Text' }
  ], processor: 'gif' },
  { id: 'video-to-gif', tags: ['shrink', 'kb', 'mb', 'passport', 'visa', 'photo chota karo', 'size reduce', 'image size', 'make smaller', 'compress', 'resize', 'convert', 'crop'], name: 'Video to GIF', slug: 'video-to-gif', category: 'gif-tools', icon: 'Video', accentColor: '#059669', description: 'Convert short video clips (MP4, WebM) into looping GIFs', metaTitle: 'Convert Video to GIF', metaDescription: 'Create GIFs from videos.', acceptedFormats: ['video/mp4', 'video/webm'], maxFileSize: 100 * 1024 * 1024, multiFile: false, options: [], processor: 'gif', comingSoon: true }
];

export function getToolsByCategory(categoryId: CategoryId): ToolConfig[] {
  return tools.filter(t => t.category === categoryId);
}

export function getPopularTools(limit: number): ToolConfig[] {
  return tools.slice(0, limit);
}
